---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

bases:
  - ../single
patches:
  - deploy.yml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vault
  path: patch.yaml

secretGenerator:
  - files:
      - config/autounseal.hcl
    behavior: merge
    name: vault
