---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - demo.yml

configMapGenerator:
  - files:
      - config/agent.hcl
    name: vault-agent
  - files:
      - config/default.conf
    name: nginx
