---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccount: vault
      containers:
        - image: prom/statsd-exporter:v0.12.2
          name: statsd-exporter
          ports:
            - name: statsd-port
              containerPort: 9125
            - name: metrics
              containerPort: 9102
        - image: vault:1.2.2
          name: vault
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: VAULT_API_ADDR
              value: http://$(POD_IP):8200
            - name: VAULT_CLUSTER_ADDR
              value: http://$(POD_IP):8201
            - name: VAULT_LOG_LEVEL
              value: info
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          command:
            - vault
            - server
            - -config=/etc/vault/config.hcl
          ports:
            - name: http
              containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: /etc/vault
      volumes:
        - name: config
          secret:
            secretName: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - name: http
      port: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  labels:
    k8s-app: statsd-exporter
spec:
  ports:
    - name: metrics
      port: 9102
  selector:
    app: vault
