---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - deploy.yml
  - sm.yml
  - rbac.yml
  - ns.yml

secretGenerator:
  - files:
      - config/config.hcl
    name: vault
