---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - deploy.yml
  - sm.yml
  - rbac.yml
  - ns.yml

secretGenerator:
  - files:
      - config/config.hcl
    name: vault

images:
  - name: prom/statsd-exporter
    newName: prom/statsd-exporter
    newTag: v0.19.1
  - name: vault
    newName: vault
    newTag: 1.6.2
